#name: Deploy spider fan
#
#on:
#  push:
#
#jobs:
#  deploy_api:
#    runs-on: self-hosted
#    steps:
#      - name: checkout
#        uses: actions/checkout@v4
#      - name: run
#        env:
#          PORT: ${{secrets.PORT}}
#        run: |
#          curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
#          . ~/.nvm/nvm.sh
#          npm install
#          sudo pkill -f node
#          sudo -E nohup $(which node) ./bin/www


name: Deploy Frontend

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to dockerhub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/spdr .
          docker push ${{secrets.DOCKER_USERNAME}}/spdr:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Prune unused images
        run: sudo docker system prune --force
      - name: Pull image from docker
        run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/spdr:latest
      - name: Delete old container
        run: sudo docker rm -f spdr-frnt
      - name: Run container
        run: sudo docker run -d -e POSTGRES_HOST="${{secrets.POSTGRES_HOST}}" -e POSTGRES_PORT="${{secrets.POSTGRES_PORT}}" -e POSTGRES_USER="${{secrets.POSTGRES_USER}}" -e POSTGRES_PASSWORD="${{secrets.POSTGRES_PASSWORD}}" -e POSTGRES_DB="${{secrets.POSTGRES_DB}}" -p 80:3000 --name spdr-frnt ${{secrets.DOCKER_USERNAME}}/spdr:latest